[package]
name = "bri"
description = "The Brainrot interepreter for brainfuck"
version = "0.1.0"
authors = ["Prajwal S N <prajwalnadig21@gmail.com>"]
edition = "2021"

[lib]

[[bin]]
name = "bri"
path = "src/main.rs"

[dependencies]
